# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  release:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: [linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd ../../x5gon/x5gon-discovery
          git pull
          npm install
          npm run-script build
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
